### ISSUE TITLE
There was a problem trying to request the code.

### ISSUE THREAD

**Issue by ghost** [lucasvdh/laravelwhatsapp#2]
There was a problem trying to request the code.
`\chat-api\src\Registration.php
  $this->eventManager()->fire('onCodeRequestFailed',
                    [
                        $this->phoneNumber,
                        $method,
                        $response->reason,
                        isset($response->param) ? $response->param : null,
                    ]);
                throw new Exception('There was a problem trying to request the code.');
`

i inspect the error and found this response:
`{#178 ▼
  +"login": "972567940999"
  +"status": "fail"
  +"reason": "old_version"
}`

my code:
`
 $phone_number = '972567940999';
        $type = 'sms';
        $result = \Whatsapp::requestCode($phone_number, $type);
`

**Comment by lucasvdh** [comment]
I am no longer maintaining this package because the library which this depends on is also deprecated and no longer updated. If you receive an error message that an old version is used I'm afraid this has finally stopped working.

So for now we're stuck waiting for when Whatsapp releases their business API. But this might take a long time.
